# データベース接続設定
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/UserManagementSystemDB
spring.datasource.username=postgres
spring.datasource.password=postgres